### ISSUE TITLE
Version control the Fan01 clothing sources.

### ISSUE THREAD

**Issue by Hoikas** [H-uru/moul-assets#257]
The max files for GlobalClothing_District_[Fem|M]ale01.prp were uploaded to the OU discord today https://discord.com/channels/282045216221822978/863924968747958333/1287513197368316008. They should be added to the appropriate place in the repository. Uploading zip here in the interim.

[GlobalClothing.Chloe.20131203.zip](https://github.com/user-attachments/files/17091612/GlobalClothing.Chloe.20131203.zip)

**Comment by dgelessus** [comment]
By the way, there are [a couple of branches](https://foundry.openuru.org/gitblit/log/?r=Foundry/Foundry-MOULa-Delivery.git&h=Chloe/FanClothing-2013.12.03) in the OpenUru [Foundry-MOULa-Delivery](https://foundry.openuru.org/gitblit/summary/?r=Foundry/Foundry-MOULa-Delivery.git) repo that also contain source files for these PRPs. It might be worth checking that those files match up with what rarified uploaded now, because apparently there were multiple revisions (I *assume* they are identical though, based on the name of the zip file). (cc @dpogue)

**Comment by dpogue** [comment]
Just checked and it appears that the linked zip file is the latest version, but there is an open question about whether any hand-modifications have been made to the Fan01 PRP files since the original export.

**Comment by Hoikas** [comment]
It looks like, on our end, the only changes to the Fan01 PRPs have been just round-tripping them through libHSPlasma.
